### ISSUE TITLE
Structure of parameters

### ISSUE THREAD

**Issue by tetsuobe** [LendoSTPGdansk/lendo-infrastructure-bundle#31]
Enhance parameters.yml to be more structurized and more readable.

**Comment by tetsuobe** [comment]
Example:
```
parameters:
  event_storage: cassandra
  cassandra:
    client: lendiservice
    endpoint: eventstorage
    port: 9042
    keyspace: keyspace,
    username: user
    password: passwd
  cassandra_test:
    endopoint: eventstorage_test
```
